name: Run Code Quality Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  spotless:
    name: Run Spotless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create keys.properties
        run: |
          echo "api.host=${{ secrets.API_HOST }}" > keys.properties

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Auto-fix Spotless issues
        run: ./gradlew spotlessApply
        if: failure()

  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest
    needs: spotless
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create keys.properties
        run: |
          echo "api.host=${{ secrets.API_HOST }}" > keys.properties

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Detekt
        run: ./gradlew detekt
