name: Run Code Quality Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  spotless:
    name: Run Spotless
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Auto-fix Spotless issues
        run: ./gradlew spotlessApply
        if: failure()

  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest
    needs: spotless
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run Detekt
        run: ./gradlew detekt
